// This file has been automatically generated by genstub
#include <assert.h>
#include <string.h>
#include "py/dynruntime.h"
// ESP-IDF imports
#include <esp_err.h>
#include <driver/adc.h>
#include <esp_adc_cal.h>

STATIC mp_obj_t espidf_esp_err_to_name(mp_obj_t arg0) {
	// convert arg0
	uint val0 = (uint)mp_obj_get_int(arg0);
	// call
	const char* ret = esp_err_to_name(val0);
	return ret ? mp_obj_new_str(ret, strlen(ret)) : mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(espidf_esp_err_to_name_obj, espidf_esp_err_to_name);

STATIC mp_obj_t espidf_esp_adc_cal_characterize(size_t n_args, const mp_obj_t *args) {
	// convert args[0]
	uint val0 = (uint)mp_obj_get_int(args[0]);
	// convert args[1]
	uint val1 = (uint)mp_obj_get_int(args[1]);
	// convert args[2]
	uint val2 = (uint)mp_obj_get_int(args[2]);
	// convert args[3]
	uint val3 = (uint)mp_obj_get_int(args[3]);
	// convert args[4]
	void *val4 = 0;
	if (args[4] != mp_const_none) {
		mp_buffer_info_t val4_buf;
		mp_get_buffer_raise(args[4], &val4_buf, MP_BUFFER_RW);
		val4 = (void *)(val4_buf.buf);
	}
	// call
	const uint ret = esp_adc_cal_characterize(val0, val1, val2, val3, val4);
	return mp_obj_new_int(ret);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(espidf_esp_adc_cal_characterize_obj, 5, 5, espidf_esp_adc_cal_characterize);

STATIC mp_obj_t espidf_esp_adc_cal_raw_to_voltage(mp_obj_t arg0, mp_obj_t arg1) {
	// convert arg0
	uint val0 = (uint)mp_obj_get_int(arg0);
	// convert arg1
	void *val1 = 0;
	if (arg1 != mp_const_none) {
		mp_buffer_info_t val1_buf;
		mp_get_buffer_raise(arg1, &val1_buf, MP_BUFFER_RW);
		val1 = (void *)(val1_buf.buf);
	}
	// call
	const uint ret = esp_adc_cal_raw_to_voltage(val0, val1);
	return mp_obj_new_int(ret);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_2(espidf_esp_adc_cal_raw_to_voltage_obj, espidf_esp_adc_cal_raw_to_voltage);

mp_obj_t mpy_init(mp_obj_fun_bc_t *self, size_t n_args, size_t n_kw, mp_obj_t *args) {
	MP_DYNRUNTIME_INIT_ENTRY
	mp_store_global(MP_QSTR_esp_err_to_name, MP_OBJ_FROM_PTR(&espidf_esp_err_to_name_obj));
	mp_store_global(MP_QSTR_esp_adc_cal_characterize, MP_OBJ_FROM_PTR(&espidf_esp_adc_cal_characterize_obj));
	mp_store_global(MP_QSTR_esp_adc_cal_raw_to_voltage, MP_OBJ_FROM_PTR(&espidf_esp_adc_cal_raw_to_voltage_obj));
	MP_DYNRUNTIME_INIT_EXIT
}
